vrend: Make vrend_report_buffer_error a macro
So the caller is correctly printed, from:

vrend_report_buffer_error: context error reported 1 "deqp-gles31" Illegal command buffer 14091265

to:

vrend_decode_block: context error reported 1 "deqp-gles31" Illegal command buffer 14091265

Signed-off-by: Tomeu Vizoso <tomeu.vizoso@collabora.com>
Reviewed-by: Gert Wollny <gert.wollny@collabora.com>